import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  GoogleOneTap,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI Course Generator",
  description: "Generated by create next app",
  icons: {
        icon: '/favicon.ico',
      }
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
      <GoogleOneTap/>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
